version: '3.8'
services:
  cache-db:
    image: redis:6.0.7
    restart: always
    container_name: cache-db
    # volumes:
     # - redis_volume_data:/data
    ports:
      - 6379:6379
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 5000:5000
    restart: always
    container_name: e-commerce-backend
    depends_on:
      - cache-db   

# volumes:
  #redis_volume_data: 
