version: '3.8'
services:
  cache-db:
    image: redis:6.0.7
    restart: always
    # volumes:
     # - redis_volume_data:/data
    ports:
      - 6379:6379
  test-db:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: 123456    

# volumes:
  #redis_volume_data: 
